"""
Shared ISL alphabet asset utilities.

One stable reference image per A-Z label lives in ``static/assets/isl_alphabet/``
(generated by ``generate_alphabet_assets.py`` from the bundled training data).
Both the Flask app and the CLI utilities (text_to_isl.py, speech_to_isl.py)
resolve letters through this module so they never depend on a missing
``data/A..Z`` directory or a hardcoded drive path.
"""

from pathlib import Path

import cv2
import numpy as np

# Repository root = parent of the folder containing this file.
PROJECT_ROOT = Path(__file__).resolve().parent

ASSET_DIR = PROJECT_ROOT / "static" / "assets" / "isl_alphabet"
OUTPUT_DIR = PROJECT_ROOT / "static" / "isl_output"

ISL_LABELS = [chr(i) for i in range(ord("A"), ord("Z") + 1)]

TARGET_SIZE = 100          # px, per-letter tile size in composite images
MAX_CHARS_PER_LINE = 10    # wrap after 10 letters per line


def asset_path_for_letter(letter: str) -> Path:
    """Return the expected path of a single-letter reference asset."""
    return ASSET_DIR / f"{letter.upper()}.png"


def load_letter_image(letter: str, target_size: int = TARGET_SIZE):
    """
    Load the reference image for a letter, resized to target_size x target_size
    BGR. Returns None when the asset has not been generated yet.
    """
    path = asset_path_for_letter(letter)
    if not path.is_file():
        return None
    img = cv2.imread(str(path), cv2.IMREAD_UNCHANGED)
    if img is None:
        return None
    img = cv2.resize(img, (target_size, target_size))
    if len(img.shape) == 2:  # grayscale asset -> BGR
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    return img


def assets_available() -> bool:
    """True when every A-Z reference asset exists on disk."""
    return all(asset_path_for_letter(letter).is_file() for letter in ISL_LABELS)


def missing_assets() -> list:
    """Letters whose reference asset is not generated yet."""
    return [letter for letter in ISL_LABELS if not asset_path_for_letter(letter).is_file()]


def chunk_list(lst, n):
    return [lst[i:i + n] for i in range(0, len(lst), n)]


def pad_image_width(img, target_width):
    h, w = img.shape[:2]
    if w == target_width:
        return img
    pad_width = target_width - w
    if len(img.shape) == 3:
        pad_shape = (h, pad_width, img.shape[2])
    else:
        pad_shape = (h, pad_width)
    padding = np.ones(pad_shape, dtype=np.uint8) * 255
    return np.concatenate((img, padding), axis=1)


def build_composite(isl_images):
    """
    Horizontally tile letter tiles (wrapping every MAX_CHARS_PER_LINE letters,
    white padding between lines) and return the combined BGR image.
    """
    if not isl_images:
        return None
    lines = chunk_list(isl_images, MAX_CHARS_PER_LINE)
    h_concat_lines = []
    max_width = 0
    for line_imgs in lines:
        h_concat = cv2.hconcat(line_imgs)
        h_concat_lines.append(h_concat)
        max_width = max(max_width, h_concat.shape[1])
    h_concat_lines = [pad_image_width(line, max_width) for line in h_concat_lines]
    return cv2.vconcat(h_concat_lines)


def cleanup_old_outputs(keep_seconds: int = 3600, now=None) -> int:
    """
    Delete generated finger-spelling images in OUTPUT_DIR older than
    ``keep_seconds``. Only files matching ``isl_<hex>.png`` are ever removed,
    so anything else that lives in the folder (including git-tracked sample
    outputs) is safe. Returns the number of files deleted.
    """
    import re
    import time as _time

    if now is None:
        now = _time.time()
    pattern = re.compile(r"^isl_[0-9a-f]{32}\.png$")
    removed = 0
    if not OUTPUT_DIR.is_dir():
        return 0
    for entry in OUTPUT_DIR.iterdir():
        if not entry.is_file() or not pattern.match(entry.name):
            continue
        try:
            if now - entry.stat().st_mtime > keep_seconds:
                entry.unlink()
                removed += 1
        except OSError:
            # File locked or being served right now - skip it this round.
            continue
    return removed
